version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: main/Databases/dockerfile
    container_name: my-postgres-container
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: main/dockerfile
    container_name: my-python-app
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_CONNECTION_PATH: "/app/configs/DatabaseConfigs/postgresql.yaml"
      LLM_CONFIG_PATH: "/app/configs/LLMConfigs/bedrock.yaml"
    ports:
      - "8000:8000"

volumes:
  postgres-data:
