FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . /app

# Make port 8051 available to the world outside this container
EXPOSE 8051

# Define environment variable
ENV NAME StreamlitApp

# Run Streamlit app when the container launches
CMD ["streamlit", "run", "ui/app.py", "--server.port=8051", "--server.address=0.0.0.0"]
